### ISSUE TITLE
HTTP Error 401: Unauthorized when running setup.py

### ISSUE THREAD

**Issue by TWCunningham** [zak-45/Broadlink-Domoticz-plugin#1]
I believe I have Domoticz installed OK and have downloaded the plugin files, but when I run setup.py I get this:

tom@raspberrypi:~/domoticz/plugins/Broadlink $ sudo python setup2.py
*
================================================================================
*
                     Broadlink Plugin Installation
*
================================================================================
*
Python 3.9.2 (default, Mar 12 2021, 04:06:34)
[GCC 10.2.1 20210110] on linux
________________________________________
# We need Domoticz Net info
----------------------------------------
ENTER Domoticz IP address (e.g. 192.168.1.45): 192.168.0.10
ENTER Domoticz Port Number (e.g. 8080): 8080
IP/PORT OK
Installation initialized ......
________________________________________
# we retrieve Domoticz language
Traceback (most recent call last):
  File "/home/tom/domoticz/plugins/Broadlink/setup2.py", line 74, in exe_domoticz
    html = urllib.request.urlopen('http://' + str(Domoticz) + ':' + str(Port) + '/json.htm?' + params, timeout=20)
  File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

Error sending command to Domoticz :type=settings

Interestingly, I can get the same error by typing http://192.168.0.10:8080/json.htm?type:setting into my browser, even after clearing the browser cache. Any suggestions?

**Comment by TWCunningham** [comment]
Well, never mind, looks like this has been addressed over in the Domoticz webboard (although I'm not sure what local LAN username and password means). Closing for now.
